language: perl
sudo: false

install:
  - perlbrew list
  - cpanm https://dist.wdlabs.com/Alien-Apache24-0.05.tar.gz -v
  - alien-apache24-install-mod_perl
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps --missing | cpanm -n

perl:
  - "5.8"
  - "5.10"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"

script:
  - dzil test -v
